version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vyaparsathi-backend
    restart: always
    env_file:
      - backend.env
    ports:
      - "8548:8548"
    networks:
      - vyaparsathi-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vyaparsathi-frontend
    restart: always
    ports:
      - "5173:80"
    networks:
      - vyaparsathi-network

networks:
  vyaparsathi-network:
    driver: bridge
